[versions]
kotlin = "2.3.10"
ktlint = "14.0.1"
mavenPublish = "0.36.0"
fatbinary = "1.0"
coroutines = "1.10.2"
junit = "6.0.3"
clikt = "5.1.0"
jackson = "2.21.1"

[libraries]
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
clikt = { group = "com.github.ajalt.clikt", name = "clikt", version.ref = "clikt" }
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
jackson-dataformat-yaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml", version.ref = "jackson" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
fatbinary = { id = "io.github.cdsap.fatbinary", version.ref = "fatbinary" }
